# Generated by Django 4.0.6 on 2022-09-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0002_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img',
            field=models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/noticias'),
        ),
    ]
