# Generated by Django 4.0.6 on 2022-09-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0004_alter_noticia_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='img',
        ),
        migrations.AddField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/noticias'),
        ),
    ]
