# Generated by Django 4.0.6 on 2022-09-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0005_remove_noticia_img_noticia_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='image',
            new_name='img',
        ),
    ]
